### ISSUE TITLE
I'm having an issue decrypting the unity3d files.

### ISSUE THREAD

**Issue by TheSilverSmith** [hampta/WOG-dump#2]
Running the script successfully saved a ton of unity3d assets to the assets folder. According to the command window, I've also successfully downloaded all the decryption keys. However, when the script goes to decrypt the assets, the script crashes, and I'm not sure why. 

The keys.txt file is empty, but I'm not sure if that's relevant. My encrypted and decrypted folders appear to be empty as well. 

![image](https://github.com/user-attachments/assets/1b686745-732d-40dd-95a9-ac0a8c0ba49a)

**Comment by TheSilverSmith** [comment]
This message briefly appears before the tracebacks begin.
![image](https://github.com/user-attachments/assets/7b24e860-32b5-4eda-a36f-808d5fa78c23)
It might be related to an error about downloading a unity3d file, but as far as I know, all the unity3d files are already downloaded in my assets folder.

**Comment by hampta** [comment]
> This message briefly appears before the tracebacks begin.
> ![image](https://github.com/user-attachments/assets/7b24e860-32b5-4eda-a36f-808d5fa78c23)
> It might be related to an error about downloading a unity3d file, but as far as I know, all the unity3d files are already downloaded in my assets folder.

Try to take the keys from the repository and run the script again, but do not update the keys.

**Comment by hampta** [comment]
> This message briefly appears before the tracebacks begin.
> ![image](https://github.com/user-attachments/assets/7b24e860-32b5-4eda-a36f-808d5fa78c23)
> It might be related to an error about downloading a unity3d file, but as far as I know, all the unity3d files are already downloaded in my assets folder.

Try to take the keys from the repository and run the script again, but do not update the keys.

**Comment by hampta** [comment]
something broke in getting the key, I don't have time for it at the moment. I'll fix it later.

**Comment by hampta** [comment]
If you need files, write to telegram @hampta, I'll send you the link

**Comment by hampta** [comment]
fixed in [763c747](https://github.com/hampta/WOG-dump/commit/763c74765fe820df3f77b58baf299200266eaab6) commit

**Comment by hampta** [comment]
and finally fixed in latest commits
