### ISSUE TITLE
How do I install and run the decryption script?

### ISSUE THREAD

**Issue by goods114514** [hampta/WOG-dump#6]
I know it's stupid to ask this question on github... But I really wanted to extract the game model to make some 3D printed model toys. Here are the files I might need to sort out, I put them in a folder but nothing happens when I run the wog dump.py.
![Screenshot 2024-08-29 205028](https://github.com/user-attachments/assets/8d63878c-fccb-44a1-9eaf-fdf379870929)
![Screenshot 2024-08-29 205101](https://github.com/user-attachments/assets/2ac8c2e8-e631-4288-8324-7a4ccd10ee71)

**Comment by hampta** [comment]
You are doing it wrong, the script does everything itself - downloads and decrypts files. Decrypted files are in the folder `./assets/decrypted/`

**Comment by goods114514** [comment]
I'm glad you were able to give me such a quick reply, and I'll make sure again, that amazing automation script is wog dump.py, right?

**Comment by hampta** [comment]
Yes, Instructions for use are on the project page

**Comment by goods114514** [comment]
![Screenshot 2024-08-29 215219](https://github.com/user-attachments/assets/75e6b415-5b1e-4365-a7f3-4e898d7e1fa7)
Oh my God, here's what's going on

**Comment by hampta** [comment]
Everything is written on the page, I close the issue
